version: "3.8"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - groupomania_data:/var/lib/mysql
      - ./groupomania.sql:/docker-entrypoint-initdb.d/groupomania.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80

volumes:
  groupomania_data:
